// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate
// Run with: dotnet run --project Codegen~/round-trip/
//
// AOT/IL2CPP note: the DTOs use System.Text.Json [JsonPropertyName] attributes.
// Source-generated serialization (JsonSerializerContext) — required for IL2CPP —
// is deferred until Unity can compile the package (task 3.4 in plan-b.md).

using System.Text.Json;
using ElevenLabs.Protocol;

static string Roundtrip<T>(T instance) where T : notnull
{
    var json = JsonSerializer.Serialize(instance);
    var back = JsonSerializer.Deserialize<T>(json)
        ?? throw new InvalidOperationException($"Deserialize<{typeof(T).Name}> returned null");
    var roundTripped = JsonSerializer.Serialize(back);
    if (json != roundTripped)
        throw new InvalidOperationException(
            $"Round-trip mismatch for {typeof(T).Name}:\n  before: {json}\n  after:  {roundTripped}");
    return json;
}

// --- IncomingSocketEvent subtypes ---
Console.WriteLine(Roundtrip(new ConversationInitiationMetadata()));
Console.WriteLine(Roundtrip(new AgentResponseComplete()));
Console.WriteLine(Roundtrip(new UserTranscript()));
Console.WriteLine(Roundtrip(new AgentResponse()));
Console.WriteLine(Roundtrip(new AgentResponseCorrection()));
Console.WriteLine(Roundtrip(new AudioResponse()));
Console.WriteLine(Roundtrip(new Interruption()));
Console.WriteLine(Roundtrip(new VadScore()));
Console.WriteLine(Roundtrip(new ClientToolCall()));
Console.WriteLine(Roundtrip(new AgentToolResponseFullPayload()));
Console.WriteLine(Roundtrip(new Ping()));

// --- OutgoingSocketEvent subtypes ---
Console.WriteLine(Roundtrip(new UserAudioChunk()));
Console.WriteLine(Roundtrip(new UserMessage()));
Console.WriteLine(Roundtrip(new UserActivity()));
Console.WriteLine(Roundtrip(new MultimodalMessage()));
Console.WriteLine(Roundtrip(new Pong()));
Console.WriteLine(Roundtrip(new ClientToolResult()));
Console.WriteLine(Roundtrip(new ContextualUpdate()));
Console.WriteLine(Roundtrip(new ConversationInitiationClientData()));

Console.WriteLine("All round-trips passed.");
