// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate
// Run with: dotnet run --project Codegen~/round-trip/
//
// AOT/IL2CPP note: the DTOs use Newtonsoft.Json [JsonProperty] attributes.
// The Unity package consumer pulls in `com.unity.nuget.newtonsoft-json` (v3.x,
// wrapping Newtonsoft.Json 13.0.1) which ships an AOT-friendly build for
// IL2CPP/WebGL out of the box — no source-generator dance required.

using Newtonsoft.Json;
using ElevenLabs.Protocol;

static string Roundtrip<T>(T instance) where T : notnull
{
    var json = JsonConvert.SerializeObject(instance);
    var back = JsonConvert.DeserializeObject<T>(json)
        ?? throw new InvalidOperationException($"Deserialize<{typeof(T).Name}> returned null");
    var roundTripped = JsonConvert.SerializeObject(back);
    if (json != roundTripped)
        throw new InvalidOperationException(
            $"Round-trip mismatch for {typeof(T).Name}:\n  before: {json}\n  after:  {roundTripped}");
    return json;
}

// --- IncomingSocketEvent subtypes ---
Console.WriteLine(Roundtrip(new ConversationInitiationMetadata()));
Console.WriteLine(Roundtrip(new AgentResponseComplete()));
Console.WriteLine(Roundtrip(new McpToolCall()));
Console.WriteLine(Roundtrip(new ClientError()));
Console.WriteLine(Roundtrip(new GuardrailTriggered()));
Console.WriteLine(Roundtrip(new UserTranscript()));
Console.WriteLine(Roundtrip(new AgentResponse()));
Console.WriteLine(Roundtrip(new AgentResponseCorrection()));
Console.WriteLine(Roundtrip(new AgentResponseMetadata()));
Console.WriteLine(Roundtrip(new AudioResponse()));
Console.WriteLine(Roundtrip(new Interruption()));
Console.WriteLine(Roundtrip(new VadScore()));
Console.WriteLine(Roundtrip(new AgentChatResponsePart()));
Console.WriteLine(Roundtrip(new ClientToolCall()));
Console.WriteLine(Roundtrip(new AgentToolResponse()));
Console.WriteLine(Roundtrip(new AgentToolResponseFullPayload()));
Console.WriteLine(Roundtrip(new AgentToolRequest()));
Console.WriteLine(Roundtrip(new Ping()));
Console.WriteLine(Roundtrip(new McpConnectionStatus()));

// --- OutgoingSocketEvent subtypes ---
Console.WriteLine(Roundtrip(new UserAudioChunk()));
Console.WriteLine(Roundtrip(new Feedback()));
Console.WriteLine(Roundtrip(new UserMessage()));
Console.WriteLine(Roundtrip(new UserActivity()));
Console.WriteLine(Roundtrip(new MultimodalMessage()));
Console.WriteLine(Roundtrip(new Pong()));
Console.WriteLine(Roundtrip(new ClientToolResult()));
Console.WriteLine(Roundtrip(new McpToolApprovalResult()));
Console.WriteLine(Roundtrip(new ContextualUpdate()));
Console.WriteLine(Roundtrip(new ConversationInitiationClientData()));

Console.WriteLine("All round-trips passed.");
