// Generated by Bridge~/build/bundle-jslib.ts — do not edit by hand.
// Source: Bridge~/src/primitives/. Regenerate via `pnpm run build:primitives`.

var library = (function() {

//#region \0rolldown/runtime.js
	var __defProp = Object.defineProperty;
	var __exportAll = (all, no_symbols) => {
		let target = {};
		for (var name in all) {
			__defProp(target, name, {
				get: all[name],
				enumerable: true
			});
		}
		if (!no_symbols) {
			__defProp(target, Symbol.toStringTag, { value: "Module" });
		}
		return target;
	};

//#endregion

//#region src/primitives/function-pointers.ts
	var function_pointers_exports = /* @__PURE__ */ __exportAll({
		$EL_CallbackPtr: () => 0,
		$EL_SettlePtr: () => 0,
		EL_ProbeWasmTable: () => EL_ProbeWasmTable,
		EL_SetInvokeCallbackPtr: () => EL_SetInvokeCallbackPtr,
		EL_SetInvokeCallbackPtr__deps: () => EL_SetInvokeCallbackPtr__deps,
		EL_SetSettleCallback: () => EL_SetSettleCallback,
		EL_SetSettleCallback__deps: () => EL_SetSettleCallback__deps
	});
	const $EL_SettlePtr = 0;
	const $EL_CallbackPtr = 0;
	const EL_SetSettleCallback__deps = ["$EL_SettlePtr"];
	function EL_SetSettleCallback(ptr) {
		EL_SettlePtr = ptr;
	}
	const EL_SetInvokeCallbackPtr__deps = ["$EL_CallbackPtr"];
	function EL_SetInvokeCallbackPtr(ptr) {
		EL_CallbackPtr = ptr;
	}
	function EL_ProbeWasmTable() {
		return typeof Module.wasmTable !== "undefined" ? 1 : 0;
	}

//#endregion
//#region src/primitives/log.ts
	var log_exports = /* @__PURE__ */ __exportAll({ $EL_Log: () => $EL_Log });
	function $EL_Log(level, scope, msg) {
		const line = "[ElevenLabs Bridge] " + scope + ": " + msg;
		if (level === "error") console.error(line);
		else if (level === "warn") console.warn(line);
		else console.log(line);
	}

//#endregion
//#region src/primitives/registries.ts
	var registries_exports = /* @__PURE__ */ __exportAll({
		$EL_AllocateFunction: () => $EL_AllocateFunction,
		$EL_AllocateFunction__deps: () => $EL_AllocateFunction__deps,
		$EL_AllocateObject: () => $EL_AllocateObject,
		$EL_AllocateObject__deps: () => $EL_AllocateObject__deps,
		$EL_Factories: () => $EL_Factories,
		$EL_Functions: () => $EL_Functions,
		$EL_LookupFactory: () => $EL_LookupFactory,
		$EL_LookupFactory__deps: () => $EL_LookupFactory__deps,
		$EL_LookupFunction: () => $EL_LookupFunction,
		$EL_LookupFunction__deps: () => $EL_LookupFunction__deps,
		$EL_LookupObject: () => $EL_LookupObject,
		$EL_LookupObject__deps: () => $EL_LookupObject__deps,
		$EL_NextHandleId: () => 1,
		$EL_Objects: () => $EL_Objects,
		$EL_RegisterFactory: () => $EL_RegisterFactory,
		$EL_RegisterFactory__deps: () => $EL_RegisterFactory__deps,
		$EL_ReleaseFunction: () => $EL_ReleaseFunction,
		$EL_ReleaseFunction__deps: () => $EL_ReleaseFunction__deps,
		$EL_ReleaseObject: () => $EL_ReleaseObject,
		$EL_ReleaseObject__deps: () => $EL_ReleaseObject__deps
	});
	const $EL_Objects = {};
	const $EL_Functions = {};
	const $EL_Factories = {};
	const $EL_NextHandleId = 1;
	const $EL_RegisterFactory__deps = ["$EL_Factories"];
	function $EL_RegisterFactory(name, fn) {
		EL_Factories[name] = fn;
	}
	const $EL_AllocateObject__deps = ["$EL_Objects", "$EL_NextHandleId"];
	function $EL_AllocateObject(obj) {
		const handle = EL_NextHandleId++;
		EL_Objects[handle] = obj;
		return handle;
	}
	const $EL_LookupObject__deps = ["$EL_Objects"];
	function $EL_LookupObject(handle) {
		return EL_Objects[handle];
	}
	const $EL_ReleaseObject__deps = ["$EL_Objects"];
	function $EL_ReleaseObject(handle) {
		delete EL_Objects[handle];
	}
	const $EL_AllocateFunction__deps = ["$EL_Functions", "$EL_NextHandleId"];
	function $EL_AllocateFunction(fn) {
		const handle = EL_NextHandleId++;
		EL_Functions[handle] = fn;
		return handle;
	}
	const $EL_LookupFunction__deps = ["$EL_Functions"];
	function $EL_LookupFunction(handle) {
		return EL_Functions[handle];
	}
	const $EL_ReleaseFunction__deps = ["$EL_Functions"];
	function $EL_ReleaseFunction(handle) {
		delete EL_Functions[handle];
	}
	const $EL_LookupFactory__deps = ["$EL_Factories"];
	function $EL_LookupFactory(name) {
		return EL_Factories[name];
	}

//#endregion
//#region src/primitives/marshalling.ts
	var marshalling_exports = /* @__PURE__ */ __exportAll({
		$EL_EncodeReturn: () => $EL_EncodeReturn,
		$EL_EncodeReturn__deps: () => $EL_EncodeReturn__deps,
		$EL_Rehydrate: () => $EL_Rehydrate,
		$EL_Rehydrate__deps: () => $EL_Rehydrate__deps
	});
	const $EL_Rehydrate__deps = [
		"$EL_Objects",
		"$EL_Functions",
		"$EL_InvokeCallback"
	];
	function $EL_Rehydrate(value) {
		if (value === null || typeof value !== "object") return value;
		const obj = value;
		if ("$ref" in obj) return EL_Objects[obj.$ref];
		if ("$fn" in obj) return EL_Functions[obj.$fn];
		if ("$cb" in obj) {
			const handle = obj.$cb;
			return (arg) => EL_InvokeCallback(handle, JSON.stringify(arg));
		}
		if (Array.isArray(value)) return value.map((v) => EL_Rehydrate(v));
		return Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, EL_Rehydrate(v)]));
	}
	const $EL_EncodeReturn__deps = ["$EL_AllocateObject", "$EL_AllocateFunction"];
	function $EL_EncodeReturn(value, shape) {
		if (shape === "object") return { $ref: EL_AllocateObject(value) };
		if (shape === "function") return { $fn: EL_AllocateFunction(value) };
		if (shape === "void") return null;
		return value;
	}

//#endregion
//#region src/primitives/callbacks.ts
	var callbacks_exports = /* @__PURE__ */ __exportAll({
		$EL_InvokeCallback: () => $EL_InvokeCallback,
		$EL_InvokeCallback__deps: () => $EL_InvokeCallback__deps
	});
	const $EL_InvokeCallback__deps = ["$EL_CallbackPtr"];
	function $EL_InvokeCallback(handle, payload) {
		const payloadPtr = stringToNewUTF8(payload);
		try {
			{{{ makeDynCall('vii', 'EL_CallbackPtr') }}}(handle, payloadPtr);
		} finally {
			_free(payloadPtr);
		}
	}

//#endregion
//#region src/primitives/promise-settle.ts
	var promise_settle_exports = /* @__PURE__ */ __exportAll({
		$EL_Settle: () => $EL_Settle,
		$EL_Settle__deps: () => $EL_Settle__deps
	});
	const $EL_Settle__deps = ["$EL_SettlePtr"];
	function $EL_Settle(promiseId, status, payload) {
		const statusCode = status === "ok" ? 0 : 1;
		const payloadPtr = stringToNewUTF8(payload);
		try {
			{{{ makeDynCall('viii', 'EL_SettlePtr') }}}(promiseId, statusCode, payloadPtr);
		} finally {
			_free(payloadPtr);
		}
	}

//#endregion
//#region src/primitives/dispatcher.ts
	var dispatcher_exports = /* @__PURE__ */ __exportAll({
		$EL_AllocString: () => $EL_AllocString,
		$EL_DecodeReturnShape: () => $EL_DecodeReturnShape,
		$EL_ParseArgs: () => $EL_ParseArgs,
		$EL_ParseArgs__deps: () => $EL_ParseArgs__deps,
		$EL_SettleWith: () => $EL_SettleWith,
		$EL_SettleWith__deps: () => $EL_SettleWith__deps,
		EL_Free: () => EL_Free,
		EL_FunctionCallAsync: () => EL_FunctionCallAsync,
		EL_FunctionCallAsync__deps: () => EL_FunctionCallAsync__deps,
		EL_FunctionCallSync: () => EL_FunctionCallSync,
		EL_FunctionCallSync__deps: () => EL_FunctionCallSync__deps,
		EL_FunctionRelease: () => EL_FunctionRelease,
		EL_FunctionRelease__deps: () => EL_FunctionRelease__deps,
		EL_InvokeFactoryAsync: () => EL_InvokeFactoryAsync,
		EL_InvokeFactoryAsync__deps: () => EL_InvokeFactoryAsync__deps,
		EL_InvokeFactorySync: () => EL_InvokeFactorySync,
		EL_InvokeFactorySync__deps: () => EL_InvokeFactorySync__deps,
		EL_ObjectCallAsync: () => EL_ObjectCallAsync,
		EL_ObjectCallAsync__deps: () => EL_ObjectCallAsync__deps,
		EL_ObjectCallSync: () => EL_ObjectCallSync,
		EL_ObjectCallSync__deps: () => EL_ObjectCallSync__deps,
		EL_ObjectGet: () => EL_ObjectGet,
		EL_ObjectGet__deps: () => EL_ObjectGet__deps,
		EL_ObjectRelease: () => EL_ObjectRelease,
		EL_ObjectRelease__deps: () => EL_ObjectRelease__deps
	});
	function $EL_DecodeReturnShape(code) {
		return [
			"value",
			"object",
			"function",
			"void"
		][code] ?? "value";
	}
	function $EL_AllocString(s) {
		const len = lengthBytesUTF8(s) + 1;
		const buf = _malloc(len);
		stringToUTF8(s, buf, len);
		return buf;
	}
	const $EL_ParseArgs__deps = ["$EL_Rehydrate"];
	function $EL_ParseArgs(argsJsonPtr) {
		const json = argsJsonPtr ? UTF8ToString(argsJsonPtr) : "[]";
		return JSON.parse(json || "[]").map((v) => EL_Rehydrate(v));
	}
	const $EL_SettleWith__deps = ["$EL_EncodeReturn", "$EL_Settle"];
	function $EL_SettleWith(promiseId, resultOrPromise, returnShape) {
		Promise.resolve(resultOrPromise).then((result) => {
			const encoded = EL_EncodeReturn(result, returnShape);
			EL_Settle(promiseId, "ok", JSON.stringify(encoded) ?? "null");
		}).catch((e) => {
			EL_Settle(promiseId, "err", e instanceof Error ? e.message : String(e));
		});
	}
	const EL_InvokeFactoryAsync__deps = [
		"$EL_LookupFactory",
		"$EL_ParseArgs",
		"$EL_DecodeReturnShape",
		"$EL_SettleWith",
		"$EL_Settle"
	];
	function EL_InvokeFactoryAsync(factoryNamePtr, argsJsonPtr, returnShape, promiseId) {
		const name = UTF8ToString(factoryNamePtr);
		try {
			const fn = EL_LookupFactory(name);
			if (!fn) throw new Error(`Unknown factory: ${name}`);
			EL_SettleWith(promiseId, fn(...EL_ParseArgs(argsJsonPtr)), EL_DecodeReturnShape(returnShape));
		} catch (e) {
			EL_Settle(promiseId, "err", e instanceof Error ? e.message : String(e));
		}
	}
	const EL_InvokeFactorySync__deps = [
		"$EL_LookupFactory",
		"$EL_ParseArgs",
		"$EL_DecodeReturnShape",
		"$EL_EncodeReturn",
		"$EL_AllocString"
	];
	function EL_InvokeFactorySync(factoryNamePtr, argsJsonPtr, returnShape) {
		try {
			const name = UTF8ToString(factoryNamePtr);
			const fn = EL_LookupFactory(name);
			if (!fn) throw new Error(`Unknown factory: ${name}`);
			const result = fn(...EL_ParseArgs(argsJsonPtr));
			return EL_AllocString(JSON.stringify(EL_EncodeReturn(result, EL_DecodeReturnShape(returnShape))) ?? "null");
		} catch (e) {
			return EL_AllocString("!err:" + (e instanceof Error ? e.message : String(e)));
		}
	}
	const EL_ObjectCallAsync__deps = [
		"$EL_LookupObject",
		"$EL_ParseArgs",
		"$EL_DecodeReturnShape",
		"$EL_SettleWith",
		"$EL_Settle"
	];
	function EL_ObjectCallAsync(handle, methodPtr, argsJsonPtr, returnShape, promiseId) {
		const method = UTF8ToString(methodPtr);
		try {
			const obj = EL_LookupObject(handle);
			if (obj === void 0) throw new Error(`unknown handle: ${handle}`);
			const fn = obj[method];
			if (typeof fn !== "function") throw new Error(`No method '${method}' on handle ${handle}`);
			EL_SettleWith(promiseId, fn.apply(obj, EL_ParseArgs(argsJsonPtr)), EL_DecodeReturnShape(returnShape));
		} catch (e) {
			EL_Settle(promiseId, "err", e instanceof Error ? e.message : String(e));
		}
	}
	const EL_ObjectCallSync__deps = [
		"$EL_LookupObject",
		"$EL_ParseArgs",
		"$EL_DecodeReturnShape",
		"$EL_EncodeReturn",
		"$EL_AllocString"
	];
	function EL_ObjectCallSync(handle, methodPtr, argsJsonPtr, returnShape) {
		try {
			const method = UTF8ToString(methodPtr);
			const obj = EL_LookupObject(handle);
			if (obj === void 0) throw new Error(`unknown handle: ${handle}`);
			const fn = obj[method];
			if (typeof fn !== "function") throw new Error(`No method '${method}' on handle ${handle}`);
			const result = fn.apply(obj, EL_ParseArgs(argsJsonPtr));
			return EL_AllocString(JSON.stringify(EL_EncodeReturn(result, EL_DecodeReturnShape(returnShape))) ?? "null");
		} catch (e) {
			return EL_AllocString("!err:" + (e instanceof Error ? e.message : String(e)));
		}
	}
	const EL_ObjectGet__deps = ["$EL_LookupObject", "$EL_AllocString"];
	function EL_ObjectGet(handle, propPtr) {
		try {
			const prop = UTF8ToString(propPtr);
			const obj = EL_LookupObject(handle);
			if (obj === void 0) throw new Error(`unknown handle: ${handle}`);
			const value = obj[prop];
			return EL_AllocString(JSON.stringify(value) ?? "null");
		} catch (e) {
			return EL_AllocString("!err:" + (e instanceof Error ? e.message : String(e)));
		}
	}
	const EL_ObjectRelease__deps = ["$EL_ReleaseObject"];
	function EL_ObjectRelease(handle) {
		EL_ReleaseObject(handle);
	}
	const EL_FunctionCallAsync__deps = [
		"$EL_LookupFunction",
		"$EL_ParseArgs",
		"$EL_DecodeReturnShape",
		"$EL_SettleWith",
		"$EL_Settle"
	];
	function EL_FunctionCallAsync(handle, argsJsonPtr, returnShape, promiseId) {
		try {
			const fn = EL_LookupFunction(handle);
			if (!fn) throw new Error(`unknown handle: ${handle}`);
			EL_SettleWith(promiseId, fn(...EL_ParseArgs(argsJsonPtr)), EL_DecodeReturnShape(returnShape));
		} catch (e) {
			EL_Settle(promiseId, "err", e instanceof Error ? e.message : String(e));
		}
	}
	const EL_FunctionCallSync__deps = [
		"$EL_LookupFunction",
		"$EL_ParseArgs",
		"$EL_DecodeReturnShape",
		"$EL_EncodeReturn",
		"$EL_AllocString"
	];
	function EL_FunctionCallSync(handle, argsJsonPtr, returnShape) {
		try {
			const fn = EL_LookupFunction(handle);
			if (!fn) throw new Error(`unknown handle: ${handle}`);
			const result = fn(...EL_ParseArgs(argsJsonPtr));
			return EL_AllocString(JSON.stringify(EL_EncodeReturn(result, EL_DecodeReturnShape(returnShape))) ?? "null");
		} catch (e) {
			return EL_AllocString("!err:" + (e instanceof Error ? e.message : String(e)));
		}
	}
	const EL_FunctionRelease__deps = ["$EL_ReleaseFunction"];
	function EL_FunctionRelease(handle) {
		EL_ReleaseFunction(handle);
	}
	function EL_Free(ptr) {
		_free(ptr);
	}

//#endregion
//#region src/primitives/smoke-test-factory.ts
	var smoke_test_factory_exports = /* @__PURE__ */ __exportAll({
		EL_SmokeTest_RegisterMathFactory: () => EL_SmokeTest_RegisterMathFactory,
		EL_SmokeTest_RegisterMathFactory__deps: () => EL_SmokeTest_RegisterMathFactory__deps
	});
	const EL_SmokeTest_RegisterMathFactory__deps = ["$EL_RegisterFactory"];
	function EL_SmokeTest_RegisterMathFactory() {
		EL_RegisterFactory("mathFactory", () => {
			const listeners = [];
			return {
				add: (a, b) => a + b,
				addAsync: (a, b) => Promise.resolve(a + b),
				pi: Math.PI,
				addTickListener: (cb) => {
					listeners.push(cb);
					return () => {
						const idx = listeners.indexOf(cb);
						if (idx >= 0) listeners.splice(idx, 1);
					};
				},
				invokeTick: (value) => {
					[...listeners].forEach((cb) => cb(value));
				},
				invokeTickFromPromise: (value) => Promise.resolve().then(() => {
					[...listeners].forEach((cb) => cb(value));
				}),
				invokeTickN: (count) => {
					const lns = [...listeners];
					for (let i = 0; i < count; i++) for (const cb of lns) cb(i);
				},
				makeAdder: (n) => (x) => n + x,
				echo: (value) => value,
				echoAsync: (value) => Promise.resolve(value),
				bigString: (length) => "x".repeat(length)
			};
		});
	}

//#endregion
//#region src/primitives/index.ts
	const library = {
		...function_pointers_exports,
		...log_exports,
		...registries_exports,
		...marshalling_exports,
		...callbacks_exports,
		...promise_settle_exports,
		...dispatcher_exports,
		...smoke_test_factory_exports
	};

//#endregion
return library;
})();
mergeInto(LibraryManager.library, library);
