// Generated by Bridge~/build/bundle-jslib.ts — do not edit by hand.
// Source: Bridge~/src/connection/. Regenerate via `pnpm run build:connection`.

var library = (function() {


//#region src/connection/index.ts
	const library = {};

//#endregion
return library;
})();
mergeInto(LibraryManager.library, library);
