// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate

#nullable enable

namespace ElevenLabs.Protocol
{
    /// <summary>
    /// Internal fan-out from a parsed <see cref="IncomingSocketEvent"/> to one
    /// strongly-typed event per wire payload. <see cref="ElevenLabs.Agents.Conversation"/>
    /// inherits and subscribes to these so its message router can translate
    /// wire events into the args-typed user-facing event surface.
    /// </summary>
    public abstract class IncomingEventDispatcher
    {
        /// <summary>Initial metadata and configuration details for a new conversation, only sent once.</summary>
        public event System.Action<ConversationInitiationMetadata>? OnConversationInitiationMetadata;

        /// <summary>Notification that the agent has finished generating a complete response.</summary>
        public event System.Action<AgentResponseComplete>? OnAgentResponseComplete;

        /// <summary>Real-time transcriptions of user speech input.</summary>
        public event System.Action<UserTranscript>? OnUserTranscript;

        /// <summary>Text responses generated by the AI agent.</summary>
        public event System.Action<AgentResponse>? OnAgentResponse;

        /// <summary>Correction to a previous agent response.</summary>
        public event System.Action<AgentResponseCorrection>? OnAgentResponseCorrection;

        /// <summary>Synthesized audio chunks of the agent's speech response.</summary>
        public event System.Action<AudioResponse>? OnAudioResponse;

        /// <summary>Notification that the agent's current response was interrupted.</summary>
        public event System.Action<Interruption>? OnInterruption;

        /// <summary>Voice Activity Detection scoring information.</summary>
        public event System.Action<VadScore>? OnVadScore;

        /// <summary>Requests from server for client to execute specific tool functions.</summary>
        public event System.Action<ClientToolCall>? OnClientToolCall;

        /// <summary>Tool response including the tool's full result payload as a string.</summary>
        public event System.Action<AgentToolResponseFullPayload>? OnAgentToolResponseFullPayload;

        /// <summary>Server-initiated ping messages for measuring connection latency.</summary>
        public event System.Action<Ping>? OnPing;

        /// <summary>
        /// Wire types the server may add ahead of an SDK refresh land here
        /// (mirrors <c>@elevenlabs/client</c> <c>BaseConversation</c>'s
        /// <c>onDebug</c> arm).
        /// </summary>
        public event System.Action<IncomingSocketEvent>? OnUnhandled;

        protected void Dispatch(IncomingSocketEvent evt)
        {
            switch (evt)
            {
                case ConversationInitiationMetadata e:
                    OnConversationInitiationMetadata?.Invoke(e);
                    break;
                case AgentResponseComplete e:
                    OnAgentResponseComplete?.Invoke(e);
                    break;
                case UserTranscript e:
                    OnUserTranscript?.Invoke(e);
                    break;
                case AgentResponse e:
                    OnAgentResponse?.Invoke(e);
                    break;
                case AgentResponseCorrection e:
                    OnAgentResponseCorrection?.Invoke(e);
                    break;
                case AudioResponse e:
                    OnAudioResponse?.Invoke(e);
                    break;
                case Interruption e:
                    OnInterruption?.Invoke(e);
                    break;
                case VadScore e:
                    OnVadScore?.Invoke(e);
                    break;
                case ClientToolCall e:
                    OnClientToolCall?.Invoke(e);
                    break;
                case AgentToolResponseFullPayload e:
                    OnAgentToolResponseFullPayload?.Invoke(e);
                    break;
                case Ping e:
                    OnPing?.Invoke(e);
                    break;
                default:
                    OnUnhandled?.Invoke(evt);
                    break;
            }
        }
    }
}
