// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate

#nullable enable

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace ElevenLabs.Protocol
{
    /// <summary>Initial metadata and configuration details for a new conversation, only sent once.</summary>
    public record ConversationInitiationMetadataArgs(
        string ConversationId,
        string AgentOutputAudioFormat,
        string UserInputAudioFormat
    );

    /// <summary>Notification that the agent has finished generating a complete response.</summary>
    public record AgentResponseCompleteArgs(int EventId);

    /// <summary>MCP tool call event with state updates (loading, awaiting_approval, success, failure).</summary>
    public record McpToolCallArgs(JToken McpToolCallData);

    /// <summary>Error event sent when an error occurs during the conversation.</summary>
    public record ClientErrorArgs(int Code, string ErrorName, string? Message);

    /// <summary>Notification that a guardrail was triggered during the conversation.</summary>
    public record GuardrailTriggeredArgs(string GuardrailName);

    /// <summary>Real-time transcriptions of user speech input.</summary>
    public record UserTranscriptArgs(string UserTranscript, int EventId);

    /// <summary>Text responses generated by the AI agent.</summary>
    public record AgentResponseArgs(string AgentResponse, int EventId);

    /// <summary>Correction to a previous agent response.</summary>
    public record AgentResponseCorrectionArgs(
        string OriginalAgentResponse,
        string CorrectedAgentResponse,
        int EventId
    );

    /// <summary>Metadata associated with an agent response, such as custom LLM response metadata.</summary>
    public record AgentResponseMetadataArgs(Dictionary<string, dynamic> Metadata, int EventId);

    /// <summary>Synthesized audio chunks of the agent's speech response.</summary>
    public record AudioResponseArgs(
        string AudioBase64,
        int EventId,
        AudioEventAlignment? Alignment,
        bool? IsFinal
    );

    /// <summary>Notification that the agent's current response was interrupted.</summary>
    public record InterruptionArgs(int EventId);

    /// <summary>Voice Activity Detection scoring information.</summary>
    public record VadScoreArgs(double VadScore);

    /// <summary>Streaming text chunks of an agent's chat response.</summary>
    public record AgentChatResponsePartArgs(string Text, string Type, int EventId);

    /// <summary>Requests from server for client to execute specific tool functions.</summary>
    public record ClientToolCallArgs(
        string ToolName,
        string ToolCallId,
        Dictionary<string, dynamic> Parameters,
        int EventId,
        bool ExpectsResponse
    );

    /// <summary>Response from an agent tool execution including status and metadata.</summary>
    public record AgentToolResponseArgs(
        string ToolName,
        string ToolCallId,
        string ToolType,
        bool IsError,
        bool? IsBlocked,
        int EventId,
        bool IsCalled
    );

    /// <summary>Tool response including the tool's full result payload as a string.</summary>
    public record AgentToolResponseFullPayloadArgs(
        string ToolName,
        string ToolCallId,
        string ToolType,
        bool IsError,
        bool? IsBlocked,
        int EventId,
        bool IsCalled,
        string FullToolResult,
        bool? Truncated
    );

    /// <summary>Notification that the agent is requesting a tool to be executed.</summary>
    public record AgentToolRequestArgs(
        string ToolName,
        string ToolCallId,
        string ToolType,
        int EventId,
        bool ExpectsResponse,
        bool DisableInterruptions,
        int ResponseTimeoutSecs,
        string ExecutionMode
    );

    /// <summary>Server-initiated ping messages for measuring connection latency.</summary>
    public record PingArgs(int EventId, int? PingMs);

    /// <summary>MCP connection status update with integration connection states.</summary>
    public record McpConnectionStatusArgs(
        IEnumerable<McpConnectionStatusIntegrationsItem>? Integrations
    );

    /// <summary>
    /// <c>ToArgs</c> extensions that translate each wire-typed
    /// <see cref="IncomingSocketEvent"/> into the flat args record exposed on
    /// the <see cref="ElevenLabs.Agents.Conversation"/> user-facing event surface.
    /// </summary>
    public static class IncomingEventArgsExtensions
    {
        public static ConversationInitiationMetadataArgs ToArgs(
            this ConversationInitiationMetadata e
        ) =>
            new(
                ConversationId: e.ConversationInitiationMetadataEvent.ConversationId,
                AgentOutputAudioFormat: e.ConversationInitiationMetadataEvent.AgentOutputAudioFormat,
                UserInputAudioFormat: e.ConversationInitiationMetadataEvent.UserInputAudioFormat
            );

        public static AgentResponseCompleteArgs ToArgs(this AgentResponseComplete e) =>
            new(EventId: e.AgentResponseCompleteEvent.EventId);

        public static McpToolCallArgs ToArgs(this McpToolCall e) =>
            new(McpToolCallData: e.McpToolCallData);

        public static ClientErrorArgs ToArgs(this ClientError e) =>
            new(
                Code: e.ErrorEvent.Code,
                ErrorName: e.ErrorEvent.ErrorName,
                Message: e.ErrorEvent.Message
            );

        public static GuardrailTriggeredArgs ToArgs(this GuardrailTriggered e) =>
            new(GuardrailName: e.GuardrailTriggeredEvent.GuardrailName);

        public static UserTranscriptArgs ToArgs(this UserTranscript e) =>
            new(
                UserTranscript: e.UserTranscriptionEvent.UserTranscript,
                EventId: e.UserTranscriptionEvent.EventId
            );

        public static AgentResponseArgs ToArgs(this AgentResponse e) =>
            new(
                AgentResponse: e.AgentResponseEvent.AgentResponse,
                EventId: e.AgentResponseEvent.EventId
            );

        public static AgentResponseCorrectionArgs ToArgs(this AgentResponseCorrection e) =>
            new(
                OriginalAgentResponse: e.AgentResponseCorrectionEvent.OriginalAgentResponse,
                CorrectedAgentResponse: e.AgentResponseCorrectionEvent.CorrectedAgentResponse,
                EventId: e.AgentResponseCorrectionEvent.EventId
            );

        public static AgentResponseMetadataArgs ToArgs(this AgentResponseMetadata e) =>
            new(
                Metadata: e.AgentResponseMetadataEvent.Metadata,
                EventId: e.AgentResponseMetadataEvent.EventId
            );

        public static AudioResponseArgs ToArgs(this AudioResponse e) =>
            new(
                AudioBase64: e.AudioEvent.AudioBase64,
                EventId: e.AudioEvent.EventId,
                Alignment: e.AudioEvent.Alignment,
                IsFinal: e.AudioEvent.IsFinal
            );

        public static InterruptionArgs ToArgs(this Interruption e) =>
            new(EventId: e.InterruptionEvent.EventId);

        public static VadScoreArgs ToArgs(this VadScore e) =>
            new(VadScore: e.VadScoreEvent.VadScore);

        public static AgentChatResponsePartArgs ToArgs(this AgentChatResponsePart e) =>
            new(
                Text: e.TextResponsePart.Text,
                Type: e.TextResponsePart.Type,
                EventId: e.TextResponsePart.EventId
            );

        public static ClientToolCallArgs ToArgs(this ClientToolCall e) =>
            new(
                ToolName: e.ClientToolCallData.ToolName,
                ToolCallId: e.ClientToolCallData.ToolCallId,
                Parameters: e.ClientToolCallData.Parameters,
                EventId: e.ClientToolCallData.EventId,
                ExpectsResponse: e.ClientToolCallData.ExpectsResponse
            );

        public static AgentToolResponseArgs ToArgs(this AgentToolResponse e) =>
            new(
                ToolName: e.AgentToolResponseData.ToolName,
                ToolCallId: e.AgentToolResponseData.ToolCallId,
                ToolType: e.AgentToolResponseData.ToolType,
                IsError: e.AgentToolResponseData.IsError,
                IsBlocked: e.AgentToolResponseData.IsBlocked,
                EventId: e.AgentToolResponseData.EventId,
                IsCalled: e.AgentToolResponseData.IsCalled
            );

        public static AgentToolResponseFullPayloadArgs ToArgs(
            this AgentToolResponseFullPayload e
        ) =>
            new(
                ToolName: e.AgentToolResponseFullPayloadData.ToolName,
                ToolCallId: e.AgentToolResponseFullPayloadData.ToolCallId,
                ToolType: e.AgentToolResponseFullPayloadData.ToolType,
                IsError: e.AgentToolResponseFullPayloadData.IsError,
                IsBlocked: e.AgentToolResponseFullPayloadData.IsBlocked,
                EventId: e.AgentToolResponseFullPayloadData.EventId,
                IsCalled: e.AgentToolResponseFullPayloadData.IsCalled,
                FullToolResult: e.AgentToolResponseFullPayloadData.FullToolResult,
                Truncated: e.AgentToolResponseFullPayloadData.Truncated
            );

        public static AgentToolRequestArgs ToArgs(this AgentToolRequest e) =>
            new(
                ToolName: e.AgentToolRequestData.ToolName,
                ToolCallId: e.AgentToolRequestData.ToolCallId,
                ToolType: e.AgentToolRequestData.ToolType,
                EventId: e.AgentToolRequestData.EventId,
                ExpectsResponse: e.AgentToolRequestData.ExpectsResponse,
                DisableInterruptions: e.AgentToolRequestData.DisableInterruptions,
                ResponseTimeoutSecs: e.AgentToolRequestData.ResponseTimeoutSecs,
                ExecutionMode: e.AgentToolRequestData.ExecutionMode
            );

        public static PingArgs ToArgs(this Ping e) =>
            new(EventId: e.PingEvent.EventId, PingMs: e.PingEvent.PingMs);

        public static McpConnectionStatusArgs ToArgs(this McpConnectionStatus e) =>
            new(Integrations: e.McpConnectionStatusData.Integrations);
    }
}
