// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate

#nullable enable

namespace ElevenLabs.Protocol
{
    public abstract class IncomingEventDispatcher
    {
        public event System.Action<ConversationInitiationMetadata>? OnConversationInitiationMetadata;

        public event System.Action<AgentResponseComplete>? OnAgentResponseComplete;

        public event System.Action<UserTranscript>? OnUserTranscript;

        public event System.Action<AgentResponse>? OnAgentResponse;

        public event System.Action<AgentResponseCorrection>? OnAgentResponseCorrection;

        public event System.Action<AudioResponse>? OnAudioResponse;

        public event System.Action<Interruption>? OnInterruption;

        public event System.Action<VadScore>? OnVadScore;

        public event System.Action<ClientToolCall>? OnClientToolCall;

        public event System.Action<AgentToolResponseFullPayload>? OnAgentToolResponseFullPayload;

        public event System.Action<Ping>? OnPing;

        // Wire types the server may add ahead of an SDK refresh land here
        // (mirrors @elevenlabs/client BaseConversation's onDebug arm).
        public event System.Action<IncomingSocketEvent>? OnUnhandled;

        protected void Dispatch(IncomingSocketEvent evt)
        {
            switch (evt)
            {
                case ConversationInitiationMetadata e:
                    OnConversationInitiationMetadata?.Invoke(e);
                    break;
                case AgentResponseComplete e:
                    OnAgentResponseComplete?.Invoke(e);
                    break;
                case UserTranscript e:
                    OnUserTranscript?.Invoke(e);
                    break;
                case AgentResponse e:
                    OnAgentResponse?.Invoke(e);
                    break;
                case AgentResponseCorrection e:
                    OnAgentResponseCorrection?.Invoke(e);
                    break;
                case AudioResponse e:
                    OnAudioResponse?.Invoke(e);
                    break;
                case Interruption e:
                    OnInterruption?.Invoke(e);
                    break;
                case VadScore e:
                    OnVadScore?.Invoke(e);
                    break;
                case ClientToolCall e:
                    OnClientToolCall?.Invoke(e);
                    break;
                case AgentToolResponseFullPayload e:
                    OnAgentToolResponseFullPayload?.Invoke(e);
                    break;
                case Ping e:
                    OnPing?.Invoke(e);
                    break;
                default:
                    OnUnhandled?.Invoke(evt);
                    break;
            }
        }
    }
}
