// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate

#nullable enable

using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ElevenLabs.Protocol
{
    /// <summary>
    /// Polymorphic deserialiser for <see cref="IncomingSocketEvent"/>. Reads
    /// the wire-level <c>type</c> discriminator and instantiates the matching
    /// concrete payload class. Unknown discriminators fall through to <see cref="UnknownIncomingEvent"/>
    /// so <see cref="IncomingEventDispatcher.OnUnhandled"/> still fires for
    /// server-added types ahead of an SDK refresh.
    /// </summary>
    /// <remarks>
    /// Read-only — <c>CanWrite</c> returns <c>false</c>. Outgoing events serialise
    /// through their own <c>[JsonProperty("type")]</c> initialisers on the
    /// <see cref="OutgoingSocketEvent"/> subclasses.
    /// </remarks>
    public sealed class IncomingSocketEventConverter : JsonConverter
    {
        public override bool CanWrite => false;

        // Exact-match the abstract base only — never the concrete subtypes.
        // The non-generic JsonConverter base lets us write this; the
        // generic JsonConverter<T> base seals CanConvert to
        // `typeof(T).IsAssignableFrom(objectType)`, which would match every
        // subtype and re-enter this converter via the obj.ToObject<TConcrete>
        // calls below, recursing until the stack overflows (silent Unity
        // crash, no diagnostic).
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(IncomingSocketEvent);
        }

        public override object? ReadJson(
            JsonReader reader,
            Type objectType,
            object? existingValue,
            JsonSerializer serializer
        )
        {
            JObject obj = JObject.Load(reader);
            string? type = obj.Value<string>("type");
            return type switch
            {
                "conversation_initiation_metadata" => obj.ToObject<ConversationInitiationMetadata>(
                    serializer
                ),
                "agent_response_complete" => obj.ToObject<AgentResponseComplete>(serializer),
                "mcp_tool_call" => obj.ToObject<McpToolCall>(serializer),
                "client_error" => obj.ToObject<ClientError>(serializer),
                "guardrail_triggered" => obj.ToObject<GuardrailTriggered>(serializer),
                "user_transcript" => obj.ToObject<UserTranscript>(serializer),
                "agent_response" => obj.ToObject<AgentResponse>(serializer),
                "agent_response_correction" => obj.ToObject<AgentResponseCorrection>(serializer),
                "agent_response_metadata" => obj.ToObject<AgentResponseMetadata>(serializer),
                "audio" => obj.ToObject<AudioResponse>(serializer),
                "interruption" => obj.ToObject<Interruption>(serializer),
                "vad_score" => obj.ToObject<VadScore>(serializer),
                "agent_chat_response_part" => obj.ToObject<AgentChatResponsePart>(serializer),
                "client_tool_call" => obj.ToObject<ClientToolCall>(serializer),
                "agent_tool_response" => obj.ToObject<AgentToolResponse>(serializer),
                "agent_tool_response_full_payload" => obj.ToObject<AgentToolResponseFullPayload>(
                    serializer
                ),
                "agent_tool_request" => obj.ToObject<AgentToolRequest>(serializer),
                "ping" => obj.ToObject<Ping>(serializer),
                "mcp_connection_status" => obj.ToObject<McpConnectionStatus>(serializer),
                _ => new UnknownIncomingEvent(type, obj.ToString(Formatting.None)),
            };
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
        {
            throw new NotSupportedException(
                "IncomingSocketEventConverter is read-only. Outgoing events serialise via OutgoingSocketEvent subclasses' own [JsonProperty(\"type\")] initialisers."
            );
        }
    }
}
