// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate

#nullable enable

using System.Collections.Generic;

namespace ElevenLabs.Protocol
{
    /// <summary>Initial metadata and configuration details for a new conversation, only sent once.</summary>
    public record ConversationInitiationMetadataArgs(
        string ConversationId,
        string AgentOutputAudioFormat,
        string UserInputAudioFormat
    );

    /// <summary>Notification that the agent has finished generating a complete response.</summary>
    public record AgentResponseCompleteArgs(int EventId);

    /// <summary>Real-time transcriptions of user speech input.</summary>
    public record UserTranscriptArgs(string UserTranscript, int EventId);

    /// <summary>Text responses generated by the AI agent.</summary>
    public record AgentResponseArgs(string AgentResponse, int EventId);

    /// <summary>Correction to a previous agent response.</summary>
    public record AgentResponseCorrectionArgs(
        string OriginalAgentResponse,
        string CorrectedAgentResponse,
        int EventId
    );

    /// <summary>Synthesized audio chunks of the agent's speech response.</summary>
    public record AudioResponseArgs(
        string AudioBase64,
        int EventId,
        AudioEventAlignment? Alignment,
        bool? IsFinal
    );

    /// <summary>Notification that the agent's current response was interrupted.</summary>
    public record InterruptionArgs(int EventId);

    /// <summary>Voice Activity Detection scoring information.</summary>
    public record VadScoreArgs(double VadScore);

    /// <summary>Requests from server for client to execute specific tool functions.</summary>
    public record ClientToolCallArgs(
        string ToolName,
        string ToolCallId,
        Dictionary<string, dynamic> Parameters,
        int EventId,
        bool ExpectsResponse
    );

    /// <summary>Tool response including the tool's full result payload as a string.</summary>
    public record AgentToolResponseFullPayloadArgs(
        string ToolName,
        string ToolCallId,
        string ToolType,
        bool IsError,
        bool? IsBlocked,
        int EventId,
        bool IsCalled,
        string FullToolResult,
        bool? Truncated
    );

    /// <summary>Server-initiated ping messages for measuring connection latency.</summary>
    public record PingArgs(int EventId, int? PingMs);

    /// <summary>
    /// <c>ToArgs</c> extensions that translate each wire-typed
    /// <see cref="IncomingSocketEvent"/> into the flat args record exposed on
    /// the <see cref="ElevenLabs.Agents.Conversation"/> user-facing event surface.
    /// </summary>
    public static class IncomingEventArgsExtensions
    {
        public static ConversationInitiationMetadataArgs ToArgs(
            this ConversationInitiationMetadata e
        ) =>
            new(
                ConversationId: e.ConversationInitiationMetadataEvent.ConversationId,
                AgentOutputAudioFormat: e.ConversationInitiationMetadataEvent.AgentOutputAudioFormat,
                UserInputAudioFormat: e.ConversationInitiationMetadataEvent.UserInputAudioFormat
            );

        public static AgentResponseCompleteArgs ToArgs(this AgentResponseComplete e) =>
            new(EventId: e.AgentResponseCompleteEvent.EventId);

        public static UserTranscriptArgs ToArgs(this UserTranscript e) =>
            new(
                UserTranscript: e.UserTranscriptionEvent.UserTranscript,
                EventId: e.UserTranscriptionEvent.EventId
            );

        public static AgentResponseArgs ToArgs(this AgentResponse e) =>
            new(
                AgentResponse: e.AgentResponseEvent.AgentResponse,
                EventId: e.AgentResponseEvent.EventId
            );

        public static AgentResponseCorrectionArgs ToArgs(this AgentResponseCorrection e) =>
            new(
                OriginalAgentResponse: e.AgentResponseCorrectionEvent.OriginalAgentResponse,
                CorrectedAgentResponse: e.AgentResponseCorrectionEvent.CorrectedAgentResponse,
                EventId: e.AgentResponseCorrectionEvent.EventId
            );

        public static AudioResponseArgs ToArgs(this AudioResponse e) =>
            new(
                AudioBase64: e.AudioEvent.AudioBase64,
                EventId: e.AudioEvent.EventId,
                Alignment: e.AudioEvent.Alignment,
                IsFinal: e.AudioEvent.IsFinal
            );

        public static InterruptionArgs ToArgs(this Interruption e) =>
            new(EventId: e.InterruptionEvent.EventId);

        public static VadScoreArgs ToArgs(this VadScore e) =>
            new(VadScore: e.VadScoreEvent.VadScore);

        public static ClientToolCallArgs ToArgs(this ClientToolCall e) =>
            new(
                ToolName: e.ClientToolCallData.ToolName,
                ToolCallId: e.ClientToolCallData.ToolCallId,
                Parameters: e.ClientToolCallData.Parameters,
                EventId: e.ClientToolCallData.EventId,
                ExpectsResponse: e.ClientToolCallData.ExpectsResponse
            );

        public static AgentToolResponseFullPayloadArgs ToArgs(
            this AgentToolResponseFullPayload e
        ) =>
            new(
                ToolName: e.AgentToolResponseFullPayloadData.ToolName,
                ToolCallId: e.AgentToolResponseFullPayloadData.ToolCallId,
                ToolType: e.AgentToolResponseFullPayloadData.ToolType,
                IsError: e.AgentToolResponseFullPayloadData.IsError,
                IsBlocked: e.AgentToolResponseFullPayloadData.IsBlocked,
                EventId: e.AgentToolResponseFullPayloadData.EventId,
                IsCalled: e.AgentToolResponseFullPayloadData.IsCalled,
                FullToolResult: e.AgentToolResponseFullPayloadData.FullToolResult,
                Truncated: e.AgentToolResponseFullPayloadData.Truncated
            );

        public static PingArgs ToArgs(this Ping e) =>
            new(EventId: e.PingEvent.EventId, PingMs: e.PingEvent.PingMs);
    }
}
