// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate

#nullable enable

using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ElevenLabs.Protocol
{
    public abstract class OutgoingSocketEvent { }

    public class UserAudioChunk : OutgoingSocketEvent
    {
        [JsonProperty("user_audio_chunk")]
        public string UserAudioChunkData { get; set; } = "";
    }

    public class Feedback : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "feedback";

        [JsonProperty("event_id")]
        public int EventId { get; set; } = 0;

        [JsonProperty("score")]
        public string Score { get; set; } = "";
    }

    public class UserMessage : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "user_message";

        [JsonProperty("text")]
        public string? Text { get; set; }

        [JsonProperty("user_identifier")]
        public string? UserIdentifier { get; set; }
    }

    public class UserActivity : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "user_activity";
    }

    public class MultimodalMessage : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "multimodal_message";

        [JsonProperty("text")]
        public Text? Text { get; set; }

        [JsonProperty("file")]
        public File? File { get; set; }
    }

    public class Text
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "user_message";

        [JsonProperty("text")]
        public string? TextData { get; set; }

        [JsonProperty("user_identifier")]
        public string? UserIdentifier { get; set; }
    }

    public class File
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "file_input";

        [JsonProperty("file_id")]
        public string FileId { get; set; } = "";
    }

    public class Pong : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "pong";

        [JsonProperty("event_id")]
        public int EventId { get; set; } = 0;
    }

    public class ClientToolResult : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "client_tool_result";

        [JsonProperty("tool_call_id")]
        public string ToolCallId { get; set; } = "";

        [JsonProperty("result")]
        public string Result { get; set; } = "";

        [JsonProperty("is_error")]
        public bool IsError { get; set; } = false;

        [JsonProperty("error_type")]
        public string? ErrorType { get; set; }
    }

    public class McpToolApprovalResult : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "mcp_tool_approval_result";

        [JsonProperty("tool_call_id")]
        public string ToolCallId { get; set; } = "";

        [JsonProperty("is_approved")]
        public bool IsApproved { get; set; } = false;
    }

    public class ContextualUpdate : OutgoingSocketEvent
    {
        [JsonProperty("type")]
        public string Type { get; init; } = "contextual_update";

        [JsonProperty("text")]
        public string Text { get; set; } = "";

        [JsonProperty("context_id")]
        public string? ContextId { get; set; }
    }

    public class ConversationInitiationClientData : OutgoingSocketEvent
    {
        [JsonProperty("conversation_config_override")]
        public ConversationConfigOverride? ConversationConfigOverride { get; set; }

        [JsonProperty("custom_llm_extra_body")]
        public Dictionary<string, dynamic>? CustomLlmExtraBody { get; set; }

        [JsonProperty("user_id")]
        public string? UserId { get; set; }

        [JsonProperty("source_info")]
        public SourceInfo? SourceInfo { get; set; }

        [JsonProperty("branch_id")]
        public string? BranchId { get; set; }

        [JsonProperty("environment")]
        public string? Environment { get; set; }

        [JsonProperty("starting_workflow_node_id")]
        public string? StartingWorkflowNodeId { get; set; }

        [JsonProperty("dynamic_variables")]
        public Dictionary<string, dynamic>? DynamicVariables { get; set; }

        [JsonProperty("type")]
        public string Type { get; init; } = "conversation_initiation_client_data";
    }

    public class ConversationConfigOverride
    {
        [JsonProperty("asr")]
        public ConversationConfigOverrideAsr? Asr { get; set; }

        [JsonProperty("turn")]
        public ConversationConfigOverrideTurn? Turn { get; set; }

        [JsonProperty("tts")]
        public ConversationConfigOverrideTts? Tts { get; set; }

        [JsonProperty("conversation")]
        public ConversationConfigOverrideConversation? Conversation { get; set; }

        [JsonProperty("agent")]
        public ConversationConfigOverrideAgent? Agent { get; set; }
    }

    public class ConversationConfigOverrideAsr
    {
        [JsonProperty("keywords")]
        public IEnumerable<string>? Keywords { get; set; }
    }

    public class ConversationConfigOverrideTurn
    {
        [JsonProperty("soft_timeout_config")]
        public ConversationConfigOverrideTurnSoftTimeoutConfig? SoftTimeoutConfig { get; set; }
    }

    public class ConversationConfigOverrideTurnSoftTimeoutConfig
    {
        [JsonProperty("message")]
        public string? Message { get; set; }
    }

    public class ConversationConfigOverrideTts
    {
        [JsonProperty("voice_id")]
        public string? VoiceId { get; set; }

        [JsonProperty("stability")]
        public double? Stability { get; set; }

        [JsonProperty("speed")]
        public double? Speed { get; set; }

        [JsonProperty("similarity_boost")]
        public double? SimilarityBoost { get; set; }
    }

    public class ConversationConfigOverrideConversation
    {
        [JsonProperty("text_only")]
        public bool? TextOnly { get; set; }
    }

    public class ConversationConfigOverrideAgent
    {
        [JsonProperty("first_message")]
        public string? FirstMessage { get; set; }

        [JsonProperty("language")]
        public string? Language { get; set; }

        [JsonProperty("max_conversation_duration_message")]
        public string? MaxConversationDurationMessage { get; set; }

        [JsonProperty("prompt")]
        public ConversationConfigOverrideAgentPrompt? Prompt { get; set; }
    }

    public class ConversationConfigOverrideAgentPrompt
    {
        [JsonProperty("prompt")]
        public string? Prompt { get; set; }

        [JsonProperty("llm")]
        public string? Llm { get; set; }

        [JsonProperty("tool_ids")]
        public IEnumerable<string>? ToolIds { get; set; }

        [JsonProperty("native_mcp_server_ids")]
        public IEnumerable<string>? NativeMcpServerIds { get; set; }

        [JsonProperty("knowledge_base")]
        public IEnumerable<ConversationConfigOverrideAgentPromptKnowledgeBaseItem>? KnowledgeBase { get; set; }
    }

    public class ConversationConfigOverrideAgentPromptKnowledgeBaseItem
    {
        [JsonProperty("type")]
        public string Type { get; set; } = "";

        [JsonProperty("name")]
        public string Name { get; set; } = "";

        [JsonProperty("id")]
        public string Id { get; set; } = "";

        [JsonProperty("usage_mode")]
        public string? UsageMode { get; set; }
    }

    public class SourceInfo
    {
        [JsonProperty("source")]
        public string? Source { get; set; }

        [JsonProperty("version")]
        public string? Version { get; set; }
    }
}
