// <auto-generated />
// Source: Codegen~/schemas/convai-asyncapi.yml
// Generator: pnpm --dir Codegen~ run generate

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ElevenLabs.Protocol
{
    public abstract class OutgoingSocketEvent
    {
    }

    public class UserAudioChunk : OutgoingSocketEvent
    {
        [JsonPropertyName("user_audio_chunk")]
        public string UserAudioChunkData { get; set; } = "";
    }

    public class UserMessage : OutgoingSocketEvent
    {
        [JsonPropertyName("type")]
        public string Type { get; init; } = "user_message";

        [JsonPropertyName("text")]
        public string? Text { get; set; }
    }

    public class UserActivity : OutgoingSocketEvent
    {
        [JsonPropertyName("type")]
        public string Type { get; init; } = "user_activity";
    }

    public class MultimodalMessage : OutgoingSocketEvent
    {
        [JsonPropertyName("type")]
        public string Type { get; init; } = "multimodal_message";

        [JsonPropertyName("text")]
        public Text? TextData { get; set; }

        [JsonPropertyName("file")]
        public File? FileData { get; set; }

        public class Text
        {
            [JsonPropertyName("type")]
            public string? Type { get; set; }

            [JsonPropertyName("text")]
            public string? TextData { get; set; }
        }

        public class File
        {
            [JsonPropertyName("type")]
            public string? Type { get; set; }

            [JsonPropertyName("file_id")]
            public string FileId { get; set; } = "";
        }
    }

    public class Pong : OutgoingSocketEvent
    {
        [JsonPropertyName("type")]
        public string Type { get; init; } = "pong";

        [JsonPropertyName("event_id")]
        public int EventId { get; set; } = 0;
    }

    public class ClientToolResult : OutgoingSocketEvent
    {
        [JsonPropertyName("type")]
        public string Type { get; init; } = "client_tool_result";

        [JsonPropertyName("tool_call_id")]
        public string ToolCallId { get; set; } = "";

        [JsonPropertyName("result")]
        public string Result { get; set; } = "";

        [JsonPropertyName("is_error")]
        public bool IsError { get; set; } = false;

        [JsonPropertyName("error_type")]
        public string? ErrorType { get; set; }
    }

    public class ContextualUpdate : OutgoingSocketEvent
    {
        [JsonPropertyName("type")]
        public string Type { get; init; } = "contextual_update";

        [JsonPropertyName("text")]
        public string Text { get; set; } = "";
    }

    public class ConversationInitiationClientData : OutgoingSocketEvent
    {
        [JsonPropertyName("conversation_config_override")]
        public ConversationConfigOverride? ConversationConfigOverrideData { get; set; }

        [JsonPropertyName("custom_llm_extra_body")]
        public Dictionary<string, object>? CustomLlmExtraBody { get; set; }

        [JsonPropertyName("user_id")]
        public string? UserId { get; set; }

        [JsonPropertyName("source_info")]
        public SourceInfo? SourceInfoData { get; set; }

        [JsonPropertyName("branch_id")]
        public string? BranchId { get; set; }

        [JsonPropertyName("environment")]
        public string? Environment { get; set; }

        [JsonPropertyName("starting_workflow_node_id")]
        public string? StartingWorkflowNodeId { get; set; }

        [JsonPropertyName("dynamic_variables")]
        public Dictionary<string, object>? DynamicVariables { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; init; } = "conversation_initiation_client_data";

        public class ConversationConfigOverride
        {
            [JsonPropertyName("turn")]
            public Turn? TurnData { get; set; }

            [JsonPropertyName("tts")]
            public Tts? TtsData { get; set; }

            [JsonPropertyName("conversation")]
            public Conversation? ConversationData { get; set; }

            [JsonPropertyName("agent")]
            public Agent? AgentData { get; set; }

            public class Turn
            {
                [JsonPropertyName("soft_timeout_config")]
                public SoftTimeoutConfig? SoftTimeoutConfigData { get; set; }

                public class SoftTimeoutConfig
                {
                    [JsonPropertyName("message")]
                    public string? Message { get; set; }
                }
            }

            public class Tts
            {
                [JsonPropertyName("voice_id")]
                public string? VoiceId { get; set; }

                [JsonPropertyName("stability")]
                public float? Stability { get; set; }

                [JsonPropertyName("speed")]
                public float? Speed { get; set; }

                [JsonPropertyName("similarity_boost")]
                public float? SimilarityBoost { get; set; }
            }

            public class Conversation
            {
                [JsonPropertyName("text_only")]
                public bool? TextOnly { get; set; }
            }

            public class Agent
            {
                [JsonPropertyName("first_message")]
                public string? FirstMessage { get; set; }

                [JsonPropertyName("language")]
                public string? Language { get; set; }

                [JsonPropertyName("max_conversation_duration_message")]
                public string? MaxConversationDurationMessage { get; set; }

                [JsonPropertyName("prompt")]
                public Prompt? PromptData { get; set; }

                public class Prompt
                {
                    [JsonPropertyName("prompt")]
                    public string? PromptData { get; set; }

                    [JsonPropertyName("llm")]
                    public string? Llm { get; set; }

                    [JsonPropertyName("tool_ids")]
                    public List<string>? ToolIds { get; set; }

                    [JsonPropertyName("native_mcp_server_ids")]
                    public List<string>? NativeMcpServerIds { get; set; }

                    [JsonPropertyName("knowledge_base")]
                    public List<KnowledgeBaseItem>? KnowledgeBase { get; set; }

                    public class KnowledgeBaseItem
                    {
                        [JsonPropertyName("type")]
                        public string Type { get; set; } = "";

                        [JsonPropertyName("name")]
                        public string Name { get; set; } = "";

                        [JsonPropertyName("id")]
                        public string Id { get; set; } = "";

                        [JsonPropertyName("usage_mode")]
                        public string? UsageMode { get; set; }
                    }
                }
            }
        }

        public class SourceInfo
        {
            [JsonPropertyName("source")]
            public string? Source { get; set; }

            [JsonPropertyName("version")]
            public string? Version { get; set; }
        }
    }
}
